python/CoNetwork/authentication/urls.py
from authentication import views
from django.urls import path

app_name = 'authentication'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/confirm', views.confirm, name='confirm'),
    path('profile/<int:id>', views.userprofile, name='profile'),
    path('profile/change_password/', views.change_pass, name='change_password'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='log_out'),
    path('reset_password/', views.reset_password, name='reset_password'),  # НУЖНО БУДЕТ ПЕРЕРАБОТАТЬ, В ССЫЛКЕ ДОЛЖЕН БЫТЬ СПЕЦТОКЕН
    path('yandex_auth/', views.yandex_auth, name='yandex authentication')
]

python/CoNetwork/main/urls.py
from django.urls import path
from main import views
from session import views as session_views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/', views.about_us, name='about_us'),
]

python/CoNetwork/news/urls.py
from news import views
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

app_name = 'news'
urlpatterns = [
    url(r'^news/(?P<pk>\d+)/$', views.news_detail, name='news'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

python/CoNetwork/py_network/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from main import views
from session import views as session_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("contact_us", views.contact_us, name='contact_us'),
    url('', include('authentication.urls')),
    url('', include('main.urls')),
    url('', include('news.urls')),
    url('', include('session.urls')),
    #url('', include('dialogues.urls'))
]

python/CoNetwork/session/urls.py
from django.contrib import admin
from django.urls import path
from session import views

app_name = 'session'
urlpatterns = [
    path("create_session/", views.create_session, name='createsession'),
    path("session/", views.session, name='session'),
    path('join_session/', views.join_session, name='join_session'),
    path("close/", views.close, name='close'),
    path('session/<str:token>/', views.session, name="session"),
    path('create_session/', views.create_session, name="create_session"),
    ]

python/CoNetwork/main/models.py
from django.db import models
from django.contrib.auth.models import User
from session.models import Session


class ContactForm(models.Model):
    username = models.CharField(verbose_name="Имя", max_length=100)
    email = models.EmailField(verbose_name="Email")
    message = models.TextField(verbose_name="Сообщение")

    def __str__(self):
        return "{0} - ({1})".format(self.username, self.email)


class SessionMessage(models.Model):
    from_user = models.ForeignKey(to=User, name='Author', verbose_name='Author of the message', on_delete=models.CASCADE)
    session_id = models.ForeignKey(to=Session, name='Session id', verbose_name='ID of the session, in which the message was sent', on_delete=models.CASCADE)
    sending_time = models.TimeField(name='Message time', verbose_name='The moment of time when the message was sent')
    text = models.CharField(name='Message text', verbose_name='Message text', max_length=255)

    def __str__(self):
        return '{} {}: {}'.format(self.sending_time, self.from_user, self.text)

python/CoNetwork/main/forms.py
from django import forms
from main.models import ContactForm
from session.models import Session


class ContactFormF(forms.ModelForm):
    class Meta:
        model = ContactForm
        fields = ['username', 'email', 'message']


class CreateSession(forms.ModelForm):
    class Meta:
        model = Session
        fields = ['name', 'language']

python/CoNetwork/main/views.py
from django.shortcuts import render
from news.models import News
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import JsonResponse, HttpRequest, HttpResponse
from django.views.decorators.csrf import csrf_exempt

import json
import logging
from main import forms as f
from main import models


def index(request):
    news_list = News.objects.all()
    paginator = Paginator(news_list, 5)

    page = request.GET.get('page')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        news = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        news = paginator.page(paginator.num_pages)
    return render(request, template_name='index.html', context={'news': news})


def contact_us(request):
    if request.method == 'POST':
        form = f.ContactFormF(request.POST or None)
        if form.is_valid():
            form.save()
        return render(request, template_name='contact_us.html', context={"form": form})
    else:
        return render(request, template_name='contact_us.html')


def about_us(request):
    return render(request, template_name='about_us.html')


def profile(request):
    return render(request, template_name='profile.html')

python/CoNetwork/main/templates/about_us.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{%  block content %}
<div class="form">
    <h2>
        Команда разработчиков
    </h2>
    <div class="col-9">
        <h6>
            Front-end:
                Антон Иванов,
                Василий Александров,
                Печенька
        </h6>
    </div>
    <div class="col-9">
        <h6>
            Back-end:
                Никита Зайцев,
                Арсений Смирнов,
                Савелий Карпухин,
                Митя Шабат,
                Михалий Дремин,
                Ярослав Рябцев,
                Алиса Чэнь
        </h6>
    </div>
    <div class="col-9">
        <h6>
            Junior разработчики (у них лапки):
                Аня Еремеева,
                Арина Косовская,
                Роман Казарян

        </h6>
    </div>
    <ul>
    </ul>
    <p>
        Часто ли у Вас бывает, что нужно написать совместно код, и Вы ждёте, пока Ваш напарник отправит свои наработки?
        Чтобы свести подобные ситуации к минимуму и сделать Вашу работу комфортнее, мы представляем нашу программу.
        Вы сможете одновременно редактировать код,
        делать поправки или просто наблюдать за процессом работы.
        Незаменимая находка для репетиторов по программированию, ведь проводить дистанционные занятия станет ещё легче,
        и новшество для работодателей!
    </p>
    <a style="color: #ECDB04" onclick="openF()">
        Больше о нас
    </a>
    <div id="fading">
        <p>
        Памагите, нас держат взаперти в подвале одного из домов штата Техас. Нас почти не кормят и заставляют работать.
        Никаких печенек и кофе, а единственное развлечение - пасьянс на Windows 95. Спасите нас пожалуйста.
    </p>
    <a style="color: #ECDB04" onclick="closeF()">
        Закройте по прочтении (& call the police)
    </a>
    </div>
</div>
{% endblock %}

python/CoNetwork/main/templates/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en" style="min-height:100%;position:relative;max-width:98%;margin:1% 0">
<head>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CoNetwork</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/default.css' %}" rel="stylesheet">
    {% block css %} {% endblock %}

    <!-- Custom fonts for this template -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>
    <script src="{% static 'js/highlight.pack.js' %}"></script>
    <script>hljs.initHighlightingOnLoad();</script>
</head>
<body style="background-color: #141414; min-height:100%">

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-primary fixed-top" style="background-color: #202326" id="mainNav">
    <div class="container">
        <img src="{% static 'img/logo.png' %}" height=25px width=30px>
        <a class="navbar-brand" style="color: #ECDB04; margin-left:10px" href="{% url 'main:index' %}"><h3>СoNetwork</h3></a>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link navitem text_head" href="{% url 'authentication:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a  class="nav-link navitem text_head" href="{% url 'authentication:register' %}">Sign
                        Up</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a  class="nav-link navitem text_head" href="{% url 'authentication:profile' request.user.id %}">{{ request.user.username }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link navitem text_head" href="{% url 'authentication:log_out' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <span style=" margin-left:40px" class="nav-link navitem text_head" onclick="openNav()">&#9776;</span>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% language 'it' %}
<div id="mySidenav" class="sidenav">
    <ul>

    </ul>
    {% if request.user.is_authenticated %}
    <a href="{% url 'authentication:profile' request.user.id %}"><h3 class="text_head">{{ request.user.username }}</h3></a>
    {% endif %}
    <a href="/dialogues/">Dialogues</a>
    <a href="#"> {% trans "Friends" %} </a>
    <a href="/create_session/">Create session</a>
</div>
{% endlanguage %}
<!--end of nav-->
<div onclick="closeNav()" id="main">
    <div class="container-fluid"
         style="margin:100px auto;position:relative;min-height:100%;padding-left:10%; padding-right:10%;">
        {% block content %} {% endblock %}
    </div>
    <!-- Footer -->
    <footer style="background-color: #141414; padding: 25px; height: 75px; position: absolute; bottom: 0px; width: 100%">
        <div class="container">
            <div class="row">
                <p class="text" style="color: #ECDB04">Copyright &copy; CoNetwork 2018</p>
                <a style="color: #ECDB04; margin-left: 800px" href="{% url 'main:contact_us' %}">Contact Us</a>
                <a style="color: #ECDB04; margin-left: -200px" href="{% url 'main:about_us' %}">About Us</a>
            </div>
        </div>
    </footer>
</div>


<!-- Bootstrap core JavaScript -->
<script src="{% static 'js/sidenav.js' %}"></script>
<script src="{% static 'js/aboutscr.js' %}"></script>
<script src="{% static 'jquery/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
{% block js %} {% endblock %}

</body>
</html>

python/CoNetwork/main/templates/contact_us.html
{% extends 'base.html' %}
{%  block content %}
    <div class="container">
        <div class="form">
            <form method="POST">
                {% csrf_token %}
                <div class="container-fluid">
                    <div class="form-group">
                        <h2 class="text_head">Contact Us</h2>
                    </div>
                    <div class="form-group">
                        <label for="email_text">Email:</label>
                        <input name="email"  class="form-control col-4"  id="email_text" autocomplete="on" placeholder="Enter your email"/>
                    </div>
                    <div class="form-group">
                        <label for="login_text">Your name:</label>
                        <input name="username"  class="form-control col-4" id="login_text"  autocomplete="on" placeholder="Enter your name"/>
                    </div>
                    <div class="form-group">
                        <label for="login_text">Your message:</label>
                        <textarea name="message"  class="form-control" autocomplete="on" placeholder="Write your message to us" rows="6"></textarea>
                    </div>
                    {% if form.errors and request.method == 'POST'%}
                        <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                    {% elif request.method == 'POST' %}
                        <div class="alert alert-success" role="alert">Your message was send!</div>
                    {% endif %}
                    <div class="form-group" style="margin-top: 5px">
                        <button type="submit"  class="btn">Send</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

python/CoNetwork/main/templates/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}

{%  block css %}
<link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{%  block content %}
<div id="jb">
    <div id="jb1">
        <div>
            <h1 class="title"> CoNetwork</h1>
            <p class="text">Сделано программистами для программистов.<br>Шутка:( </p>
        </div>
    </div>

    <div id="jb2">
        <div>
            <p style="color: white">CoNetwork - полноценная платформа для всех, чья работа так или иначе связана с
                IT-сферой. Здесь вы сможете найти программистов в свою команду и проверить их знания, используя нашу
                технологию синхронного кода при собеседовании, которая точно выявит уровень навыков.</p>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col menu">
            <a style=" text-decoration: none;color: black" href="{% url 'authentication:register' %}">
                <h3>Зарегестрируйтесь</h3>
                <hr>
                <p>Создайте аккаунт, ответив на несколько простых вопросов. </p>
            </a>
        </div>
        <div class="col menu">
            <a style=" text-decoration: none;color: black" href="{% url 'session:create_session' %}">
                <h3>Создайте сессию</h3>
                <hr>
                <p>Выберите язык и укажите параметры, подготовив все за пару минут </p>
            </a>
        </div>
        <div style="color: black" class="col menu">
            <h3>Разошлите ссылку</h3>
            <hr>
            <p>Приглашение будет только у тех, кому Вы сами его отправите</p>
        </div>
    </div>
</div>


<div class="news">
    <h1 class="subtitle">СВЕЖИЕ НОВОСТИ</h1>
    <hr class="subtitle">
    {% for news in news %}
    <div class="form" class="news">
        <a href="{% url 'news:news' pk=news.pk %}">
            <h2 class="text_head">
                {{ news.title }}
            </h2>
            <h3 class="news-subtitle">
                {{ news.subtitle }}
            </h3>
        </a>
        <p class="">Posted by mshp32group
            on {{ news.date }}</p>
    </div>
    <hr>
    {% endfor %}

    <div class="pagination">

        {% if news.has_previous %}
        <a class="right" href="?page={{ news.previous_page_number }}">
            <button type="button" class="btn">More fresh posts &larr;</button>
        </a>
        {% endif %}
    </div>
    <div class="pagination">
        {% if news.has_next %}
        <a class="left" href="?page={{ news.next_page_number }}">
            <button type="button" class="btn">&rarr; Older posts</button>
        </a>
        {% endif %}

    </div>
</div>

{% endblock %}

{%  block js %}
<script src="{% static 'js/index.js' %}"></script>
{% endblock %}