python/CoNetwork/authentication/urls.py
from authentication import views
from django.urls import path

app_name = 'authentication'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('register/confirm', views.confirm, name='confirm'),
    path('profile/<int:id>', views.userprofile, name='profile'),
    path('profile/change_password/', views.change_pass, name='change_password'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='log_out'),
    path('reset_password/', views.reset_password, name='reset_password'),  # НУЖНО БУДЕТ ПЕРЕРАБОТАТЬ, В ССЫЛКЕ ДОЛЖЕН БЫТЬ СПЕЦТОКЕН
    path('yandex_auth/', views.yandex_auth, name='yandex authentication')
]

python/CoNetwork/main/urls.py
from django.urls import path
from main import views
from session import views as session_views
app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('about_us/', views.about_us, name='about_us'),
]

python/CoNetwork/py_network/urls.py
from django.urls import path
from django.conf.urls import url, include
from django.contrib import admin
from main import views
from session import views as session_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("contact_us", views.contact_us, name='contact_us'),
    url('', include('authentication.urls')),
    url('', include('main.urls')),
    url('', include('news.urls')),
    url('', include('session.urls')),
    #url('', include('dialogues.urls'))
]

python/CoNetwork/authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from session.models import Session
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomUser(models.Model):
    user = models.OneToOneField(verbose_name="реальный пользователь", to=User, on_delete=models.CASCADE,
                                related_name="customuser")
    AdminSessions = models.ForeignKey(verbose_name="Сессии, к котормым у него есть админки", to=Session,
                                      on_delete=models.CASCADE, null=True, blank=True)
    info = models.CharField(verbose_name="информация о юзере", max_length=255)
    photo = models.ImageField(verbose_name="фото юзера")
    #dialogs = models.ForeignKey(verbose_name="диалоги юзера", to=Dialogs)

python/CoNetwork/authentication/forms.py
from django import forms
from main.models import *
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from authentication.models import CustomUser


class FormReg(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']


class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = []


class FormChangeProf(UserChangeForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']

python/CoNetwork/authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from main import yandex_oauth
from authentication import forms as f
from authentication.models import CustomUser
# Create your views here.


def confirm(request):
    return render(request, template_name='confirm.html')


def reset_password(request):
    return render(request, template_name='reset_password.html')


def log_out(request):
    logout(request)
    return redirect('/')


def log_in(request):
    if request.method == 'POST':
        print(request.POST)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            return render(request, template_name='index.html', context={'request': request})
    return render(request, template_name='login.html')


def register(request):
    if request.method == 'POST':
        formUser = f.FormReg(request.POST)
        if formUser.is_valid():
            formUser.save()
            NewCustomUser = CustomUser(user=formUser.instance)
            NewCustomUser.save()
        return render(request, template_name='reg.html', context={'form': formUser})
    elif 'code' in request.GET:
        auth_code = request.GET.get('code')
        auth_token = yandex_oauth.get_oauth_json(auth_code)['access_token']
        user_json = yandex_oauth.get_account_info(auth_token)
        return render(request, template_name='reg.html', context={'login':user_json['login'], 'email':user_json['default_email']})
    return render(request, template_name='reg.html', context={'registered':False})


@login_required(login_url="/login/")
def change_pass(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        print(request.POST)
        if form.is_valid():
            update_session_auth_hash(request, form.save())
        return render(request, template_name='change_password.html', context={'request': request, 'form': form})
    return render(request, template_name='change_password.html')


def userprofile(request, id):
    if request.method == 'POST':
        form = f.FormChangeProf(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
        return render(request, template_name='profile.html', context={'request': request, 'form': form})
    return render(request, template_name='profile.html', context={'request': request,
                                                                  'profile': CustomUser.objects.get(id=id)})
def yandex_auth(request):
    url = yandex_oauth.get_verification_url()
    return redirect(url)

python/CoNetwork/authentication/templates/change_password.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <div class="container">
                <div class="card bg-light">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="container-fluid">
                            <div class="form-group">
                                <h2 class="card-title">Change password</h2>
                            </div>
                            <div class="form-group">
                                <label for="pass_text">Enter your old password:</label>
                                <input name="old_password" type="password" class="form-control" id="pass_text" placeholder="Enter your old password">
                            </div>
                            <div class="form-group">
                                <label for="pass_text">Enter your new password:</label>
                                <input name="new_password1" type="password" class="form-control" id="pass_text" placeholder="Enter your new password">
                            </div>
                            <div class="form-group">
                                <label for="pass_text_re">Re-enter your new password:</label>
                                <input name="new_password2" type="password" class="form-control" id="pass_text_re" placeholder="Re-enter your new password">
                            </div>
                            {% if form.errors and request.method == 'POST' %}
                                <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                            {% elif request.method == 'POST' %}
                                <div class="alert alert-success" role="alert">Password was changed!</div>
                            {% endif %}
                            <div class="form-group" style="margin-top: 5px">
                                <button type="submit"  class="btn btn-primary bg-dark">Confirm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

python/CoNetwork/authentication/templates/confirm.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row">
    <div class="col"></div>
    <div class="col">
        <div class="card bg-light">
            <form method="POST">
                {% csrf_token %}
                <div class="container-fluid" style="width: 500px">
                    <div class="form-group" style="margin-left: 100px">
                        <h2 class="card-title">Confirm your email</h2>
                    </div>
                    <div class="form-group" style="margin-left: 50px">
                        <label style="margin-left: 48px">We sent a pass-code to your email</label>
                        <label style="margin-left: 5px">Please, enter it here for complete registration</label>
                    </div>
                    <div class="form-group">
                        <input name="passcode" style="margin-left: 150px" class="form-control col-4" id="login_text"  autocomplete="on" placeholder="Pass-code"/>
                    </div>
                    <div class="form-group" style="margin-top: 5px">
                        <button type="submit" style="margin-left: 180px" class="btn btn-primary bg-dark">Complete</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col"></div>
    </div>
</div>
{% endblock %}

python/CoNetwork/authentication/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-sm"></div>
        <div class="col-sm">
            <div class="container" style="margin-top: 100px">
                <div class="form">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="container-fluid">
                            <div class="form-group">
                                <h2 class="text_head">Login page</h2>
                            </div>
                            <div class="form-group" style="margin-top: 5px">
                                <label for="login_text">Login:</label>
                                <input name="username" type="text" autocomplete="on" class="form-control" id="login_text" placeholder="Enter your login"/>
                            </div>
                            <div class="form-group">
                                <label for="pass_text">Password:</label>
                                <input name="password" type="password" class="form-control" id="pass_text" placeholder="Enter your password">
                            </div>
                            {% if not request.user.is_authenticated and request.method == "POST" %}
                                <div class="alert alert-danger" role="alert">Invalid login or password!</div>
                            {% endif %}
                            <div class="form-group">
                                <button type="submit"  class="btn">Log In</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm"></div>
    </div>
{% endblock %}

python/CoNetwork/authentication/templates/profile.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<!--here goes profile-->

<div class="form">
    {% if request.user == profile.user %}
        <form method="POST">
            <h1 class="text_ head">Profile page</h1>
            <div style="margin-top:20px" class="row">
                <div class="col">
                    <img src="{% static 'img/ava_plchldr.png' %}" width="400px" height="400px">
                    <button style="margin-top:30px" class="btn">change your avatar</button>
                </div>
                <div class="col">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <div class="form-control bg-secondary">{{ profile.user.username }}</div>
                        <hr>
                        <input class="form-control" name="email" placeholder="E-mail" value="{{ profile.user.email }}">
                        {% if form.errors and request.method == 'POST'%}
                        <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                        {% elif request.method == 'POST' %}
                        <div class="alert alert-success" role="alert">All changes saved!</div>
                        {% endif %}
                        <button type="submit" class="btn">Save</button>
                        <a class="btn" href="{% url 'main:index' %}">Cancel</a>
                    </fieldset>
                    <a class="btn" href="{% url 'authentication:change_password' %}">Change password</a>
                </div>
            </div>
        </form>
    {% else %}
        <h1 class="text_ head">Profile page</h1>
        <div style="margin-top:20px" class="row">
            <div class="col">
                <img src="{% static 'img/ava_plchldr.png' %}" width="400px" height="400px">
            </div>
            <div class="col">
                <fieldset class="form-group">
                    <div class="form-control bg-secondary">{{ profile.user.username }}</div>
                    <hr>
                    <div class="form-control bg-secondary">{{ profile.user.email }}</div>
                </fieldset>
            </div>
        </div>
    {% endif %}
</div>
</div>
<!--here profile ends-->
{% endblock %}

python/CoNetwork/authentication/templates/profile_true.html
{% extends "base.html" %}
{% block content %}
    <!--here goes profile-->
    <div class="cont_form">
        <div class="form">
        <form method="POST">
            <h1 class="text_head">Profile page</h1>
            {% csrf_token %}
            <fieldset class="form-group">
                <input class="form-control" name="username" placeholder="Login" value="{{ request.user.username }}">
                <input class="form-control" name ="email" placeholder="E-mail" value="{{ request.user.email }}">
                {% if form.errors and request.method == 'POST'%}
                    <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                {% elif request.method == 'POST' %}
                    <div class="alert alert-success" role="alert">All changes saved!</div>
                {% endif %}
                <button type="submit" class="btn btn-secondary" >Save</button>
                <a class="btn btn-secondary" href="{% url 'main:index' %}">Cancel</a>
            </fieldset>
            <a class="btn btn-secondary" href="{% url 'authentication:change_password' %}">Change password</a>
        </form>
        </div>
    </div>
    <!--here profile ends-->
{% endblock %}

python/CoNetwork/authentication/templates/reg.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-6" style="min-width:350px;">
        <div class="container">
            <div class="form">
                <form method="POST">
                    {% csrf_token %}
                    <div class="container-fluid">
                        <div class="form-group">
                            <h2 class="text_head">Registration page</h2>
                        </div>
                        <div class="form-group">
                            <label for="email_text">Email:</label>
                            <input name="email" class="form-control" id="email_text" autocomplete="on"
                                   placeholder="Enter your email" value={{email}}></input>
                        </div>
                        <div class="form-group">
                            <label for="login_text">Login:</label>
                            <input name="username" class="form-control" id="login_text" autocomplete="on"
                                   placeholder="Enter your login" value={{login}}></input>
                        </div>
                        <div class="form-group">
                            <label for="pass_text">Password:</label>
                            <input name="password1" type="password" class="form-control" id="pass_text"
                                   placeholder="Enter your password">
                        </div>
                        <div class="form-group">
                            <label for="pass_text_re">Re-enter password:</label>
                            <input name="password2" type="password" class="form-control" id="pass_text_re"
                                   placeholder="Re-enter your password">
                        </div>
                        {% if form.errors and request.method == 'POST'%}
                        <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                        {% elif request.method == 'POST' %}
                        <div class="alert alert-success" role="alert">User created successfully!</div>
                        {% endif %}
                        <div class="form-group" style="margin-top: 5px;display:inline-block;">
                            <button type="submit" class="btn">Register</button>
                        </div>
                        <a href="/yandex_auth"><img style="float:right;height:50px;width:50px;background-color:yellow;display:inline-block;"></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

python/CoNetwork/authentication/templates/reset_password.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="col"></div>
        <div class="col-6">
            <div class="container">
                <div class="card bg-light">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="container-fluid">
                            <div class="form-group">
                                <h2 class="card-title">Reset password</h2>
                            </div>
                            <div class="form-group">
                                <label for="pass_text">Enter your new password:</label>
                                <input name="new_password1" type="password" class="form-control" id="pass_text" placeholder="Enter your new password">
                            </div>
                            <div class="form-group">
                                <label for="pass_text_re">Re-enter your new password:</label>
                                <input name="new_password2" type="password" class="form-control" id="pass_text_re" placeholder="Re-enter your new password">
                            </div>
                            {% if form.errors and request.method == 'POST' %}
                                <div class="alert alert-danger" role="alert">{{ form.errors }}</div>
                            {% elif request.method == 'POST' %}
                                <div class="alert alert-success" role="alert">Password was reset!</div>
                            {% endif %}
                            <div class="form-group" style="margin-top: 5px">
                                <button type="submit"  class="btn btn-primary bg-dark">Confirm</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}